### ISSUE TITLE
Interest in Hooks?

### ISSUE THREAD

**Issue by impleri** [mmomtchev/rlayers#63]
Hi, I've started working on creating hooks for the controls to provide an easy way for creating the controls UI in React (e.g. `useZoom`, `useFullscreen`) that copy the functionality from OL. Is there any interest in adding them to rlayers directly? I may even have a few examples.

**Comment by mmomtchev** [comment]
Do you have them in a public repo?

**Comment by impleri** [comment]
Yes I do. I've segmented then off from the rest of my project: https://github.com/impleri/bedrock-viz/tree/feature/rewrite-web/web/app/hooks/rlayers

**Comment by mmomtchev** [comment]
They seem like too many one-liners and I am afraid that they will be of very limited added value - most users do not use the context object at all. I just went through the examples and the context is referenced only once - and in this case the hook won't be usable since it is inside a callback.
But thank you for the suggestion, the context object API could be improved for sure - currently it just sits there as a backdoor escape to *OpenLayers* for everything that is not handled by *rlayers*, it is very raw and not really documented.

**Comment by impleri** [comment]
No worries! That's why I asked first ;)
